baseURL = "https://happy-swanson-de6307.netlify.app/"
languageCode = "en-us"
title = "Randy Moore"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5
googleAnalytics = ""
enableRobotsTXT = false

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  header = "Software Engineer"
  description = "Passionate about Quality and Impact"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/RandyMoore"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/randal-a-moore/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/AlmadenQuicksilver.png"
  recent_posts_number = 3
  disable_share = true
